
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 16 23:40:01 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESSEQUALS = 32;
  public static final int LINDBRACKET = 15;
  public static final int PLUSPLUS = 25;
  public static final int LBRACKET = 12;
  public static final int CHAR = 44;
  public static final int CONST = 7;
  public static final int GREATEREQUALS = 30;
  public static final int EQUALS = 19;
  public static final int EQUALSEQUALS = 27;
  public static final int CONTINUE = 37;
  public static final int GREATER = 29;
  public static final int LESS = 31;
  public static final int MINUS = 18;
  public static final int SEMICOLON = 10;
  public static final int AND = 23;
  public static final int OR = 24;
  public static final int BOOL = 43;
  public static final int COMMA = 11;
  public static final int CLASS = 5;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int IF = 38;
  public static final int DOT = 14;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int MINUSMINUS = 26;
  public static final int RBRACKET = 13;
  public static final int NEW = 4;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int LCURLY = 8;
  public static final int NUMBER = 45;
  public static final int MOD = 22;
  public static final int IDENT = 42;
  public static final int BREAK = 36;
  public static final int VOID = 3;
  public static final int RINDBRACKET = 16;
  public static final int RCURLY = 9;
  public static final int ELSE = 39;
  public static final int READ = 33;
  public static final int WHILE = 41;
  public static final int NOTEQUALS = 28;
  public static final int EXTENDS = 6;
  public static final int PROG = 2;
  public static final int DO = 40;
  public static final int PRINT = 34;
}

